import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Display from './Display'
import { Providers } from '@/app/Provider'
import Layout from '@/comp/Layout'
import Increment from './Increment'




const inter = Inter({ subsets: ['latin'] })

export default function Home() {
 
  return (
    <>
      <Head>
        <title>Matix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Providers>
        <Layout>
      <main className={styles.main}>
         <Display/>
        </main>
       </Layout>
        </Providers>
    </>
  )
}
